name: botsuite

services:
  botsuite:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      APP_ENV: PROD
      COVE_CLIENT_URL: ${COVE_CLIENT_URL}
      COVE_CLIENT_SECRET: ${COVE_CLIENT_SECRET}
    container_name: botsuite
    ports:
      - "2400:2400"
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - spark


networks:
    spark:
        external: true